debian: systemd service (#79)

diff --git a/debian/idzebra-2.0-utils.postinst b/debian/idzebra-2.0-utils.postinst
--- a/debian/idzebra-2.0-utils.postinst
+++ b/debian/idzebra-2.0-utils.postinst
@@ -2,25 +2,45 @@
 
 set -e
 
-if [ "$1" != configure ]; then exit 0; fi
-
-update-alternatives --quiet --install /usr/bin/zebraidx zebraidx \
+if [ "$1" = "configure" ]; then
+    update-alternatives --quiet --install /usr/bin/zebraidx zebraidx \
        /usr/bin/zebraidx-2.0 50 \
        --slave /usr/share/man/man1/zebraidx.1.gz zebraidx.1.gz \
        /usr/share/man/man1/zebraidx-2.0.1.gz
 
-update-alternatives --quiet --install /usr/bin/zebrasrv zebrasrv \
+    update-alternatives --quiet --install /usr/bin/zebrasrv zebrasrv \
        /usr/bin/zebrasrv-2.0 50 \
        --slave /usr/share/man/man8/zebrasrv.8.gz zebrasrv.8.gz \
        /usr/share/man/man8/zebrasrv-2.0.8.gz
-
-if [ -x "/etc/init.d/zebrasrv" ]; then
-        update-rc.d zebrasrv defaults >/dev/null
-        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-                invoke-rc.d zebrasrv start || exit $?
-        else
-                /etc/init.d/zebrasrv start || exit $?
-        fi
 fi
 
+# Automatically added by dh_installsystemd/13.24.2
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+    # The following line should be removed in trixie or trixie+1
+    deb-systemd-helper unmask 'zebrasrv.service' >/dev/null || true
 
+    # was-enabled defaults to true, so new installations run enable.
+    if deb-systemd-helper --quiet was-enabled 'zebrasrv.service'; then
+        # Enables the unit on first installation, creates new
+        # symlinks on upgrades if the unit file has changed.
+        deb-systemd-helper enable 'zebrasrv.service' >/dev/null || true
+    else
+        # Update the statefile to add new symlinks (if any), which need to be
+        # cleaned up on purge. Also remove old symlinks.
+        deb-systemd-helper update-state 'zebrasrv.service' >/dev/null || true
+    fi
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/13.24.2
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+    if [ -d /run/systemd/system ]; then
+        systemctl --system daemon-reload >/dev/null || true
+        if [ -n "$2" ]; then
+            _dh_action=restart
+        else
+            _dh_action=start
+        fi
+        deb-systemd-invoke $_dh_action 'zebrasrv.service' >/dev/null || true
+    fi
+fi
+# End automatically added section
